### PR TITLE
mlflow fix use of /Shared/ and 'project' so it works with Databricks (but doesn't complain of non-writeable local paths)

### PR DESCRIPTION
**Pull request by plaurent**
This allow logging to a Databricks hosted MLflow server.

Without this fix:

- if you set project='/Shared/myYOLOv8' you will receive an error that the local path '/Shared/myYOLOv8' is not writeable.
- if you set project='myYOLOv8' then Databricks REST API will complain that you need a path with '/Users' (or '/Shared' would work too).
- the artifacts path needs to have /Shared removed because artifacts paths must always be relative.

NOTE: We'll probably want to get these fixes merged back into the mainline at some point.

### CODE REVIEW

**Comment by ghost** [comment]
Got this error while running it

```log
MLFlow: Failing init - AttributeError("'NoneType' object has no attribute 'experiment_id'")
MLFlow: Continuing without Mlflow
```

**Comment by plaurent** [comment]
> Got this error while running it
> 
> ```
> MLFlow: Failing init - AttributeError("'NoneType' object has no attribute 'experiment_id'")
> MLFlow: Continuing without Mlflow
> ```

What were you running? The script I pasted in Slack?

**Comment by plaurent** [comment]
> Got this error while running it
> 
> ```
> MLFlow: Failing init - AttributeError("'NoneType' object has no attribute 'experiment_id'")
> MLFlow: Continuing without Mlflow
> ```

Do you have mlflow installed in your env?

**Comment by ghost** [comment]
Yeah I had mlflow installed, I have the issue fixed in the PR to this branch: https://github.com/Scenerainc/ultralytics/pull/2

**Pull request merged**
